name: Musings of a Plutonian Scientist
url: http://example.org
description: Simply a place to vent "percieved" frustrations with the Plutonian Elite and Government.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
